#pragma once

#define IDS_EN_CONNECT					(_T("Connect"))
#define IDS_CN_CONNECT					(_T("打开设备"))
#define IDS_EN_DISCONNECT				(_T("Disconnect"))
#define IDS_CN_DISCONNECT				(_T("断开设备"))
#define IDS_EN_SET_PARAM				(_T("Set Param"))
#define IDS_CN_SET_PARAM				(_T("设置参数"))
#define IDS_EN_GET_PARAM				(_T("Get Param"))
#define IDS_CN_GET_PARAM				(_T("获取参数"))
#define IDS_EN_SET_PARAM_PASS			(_T("Set"))
#define IDS_CN_SET_PARAM_PASS			(_T("设置"))
#define IDS_EN_VERIFY_PARAM_PASS		(_T("Verify"))
#define IDS_CN_VERIFY_PARAM_PASS		(_T("验证"))
#define IDS_EN_ENROLL					(_T("Enroll"))
#define IDS_CN_ENROLL					(_T("登记"))
#define IDS_EN_VERIFY					(_T("Verify"))
#define IDS_CN_VERIFY					(_T("验证"))
#define IDS_EN_IDENTIFY					(_T("Identify"))
#define IDS_CN_IDENTIFY					(_T("连续比对"))
#define IDS_EN_GET_USER_COUNT			(_T("Get User Count"))
#define IDS_CN_GET_USER_COUNT			(_T("用户总数"))
#define IDS_EN_DELETE_ID				(_T("Delete ID"))
#define IDS_CN_DELETE_ID				(_T("单个删除"))
#define IDS_EN_DELETE_ALL				(_T("Delete All"))
#define IDS_CN_DELETE_ALL				(_T("全部删除"))
#define IDS_EN_IDENTIFY_TEMPLATE		(_T("Identify Template"))
#define IDS_CN_IDENTIFY_TEMPLATE		(_T("下载模板识别"))
#define IDS_EN_IDENTIFY_IMAGE			(_T("Identify Image"))
#define IDS_CN_IDENTIFY_IMAGE			(_T("下载图像识别"))
#define IDS_EN_DETECT_FINGER			(_T("Is press Finger"))
#define IDS_CN_DETECT_FINGER			(_T("检测手指"))
#define IDS_EN_GET_EMPTY_ID				(_T("Get Empty ID"))
#define IDS_CN_GET_EMPTY_ID				(_T("可注册编号"))
#define IDS_EN_GET_STATUS				(_T("Get Status"))
#define IDS_CN_GET_STATUS				(_T("获取注册状态"))
#define IDS_EN_GET_BROKEN_ID			(_T("Get Broken ID"))
#define IDS_CN_GET_BROKEN_ID			(_T("坏损模板编号"))
#define IDS_EN_UP_TEMPLATE				(_T("Up Template"))
#define IDS_CN_UP_TEMPLATE				(_T("上传模板"))
#define IDS_EN_DOWN_TEMPLATE			(_T("Down Template"))
#define IDS_CN_DOWN_TEMPLATE			(_T("下载模板"))
#define IDS_EN_DOWN_MULTI_TEMPLATE		(_T("Down Multi Tmpl"))
#define IDS_CN_DOWN_MULTI_TEMPLATE		(_T("批量下载模板"))
#define IDS_EN_UP_MULTI_TEMPLATE		(_T("Up Multi Tmpl"))
#define IDS_CN_UP_MULTI_TEMPLATE		(_T("批量上传模板"))
#define IDS_EN_GET_DEVICE_INFO			(_T("Get Device Info"))
#define IDS_CN_GET_DEVICE_INFO			(_T("获取模块信息"))
#define IDS_EN_UP_IMAGE					(_T("Up Image"))
#define IDS_CN_UP_IMAGE					(_T("上传指纹图像"))
#define IDS_EN_VERIFY_WITH_DOWN_TMPL	(_T("Verify Down Tmpl"))
#define IDS_CN_VERIFY_WITH_DOWN_TMPL	(_T("下载模板验证"))
#define IDS_EN_STOP						(_T("Stop"))
#define IDS_CN_STOP						(_T("取消操作"))
#define IDS_EN_SET_MODULE_SN			(_T("Set Module SN"))
#define IDS_CN_SET_MODULE_SN			(_T("设置模块序列号"))
#define IDS_EN_GET_MODULE_SN			(_T("Get Module SN"))
#define IDS_CN_GET_MODULE_SN			(_T("获取模块序列号"))
#define IDS_EN_OPEN						(_T("Open"))
#define IDS_CN_OPEN						(_T("打开文件"))
#define IDS_EN_SAVE						(_T("Save"))
#define IDS_CN_SAVE						(_T("保存文件"))
#define IDS_EN_STRETCH					(_T("Stretch"))
#define IDS_CN_STRETCH					(_T("拉伸显示"))
#define IDS_EN_RECEIVED_RESULT			(_T("Received Result"))
#define IDS_CN_RECEIVED_RESULT			(_T("接收到的结果	"))
#define IDS_EN_FINGER_IMAGE				(_T("Finger Image"))
#define IDS_CN_FINGER_IMAGE				(_T("指纹图像"))
#define IDS_EN_TEMPLATE					(_T("Template"))
#define IDS_CN_TEMPLATE					(_T("指纹模板"))
#define IDS_EN_PARAM_TYPE				(_T("Param Type :"))
#define IDS_CN_PARAM_TYPE				(_T("参数类型 :"))
#define IDS_EN_PARAM_VALUE				(_T("Param Value :"))
#define IDS_CN_PARAM_VALUE				(_T("参数值 :"))
#define IDS_EN_COMM_INFO				(_T("Communication Information"))
#define IDS_CN_COMM_INFO				(_T("通讯信息"))
#define IDS_EN_CON_MODE					(_T("Con Mode"))
#define IDS_CN_CON_MODE					(_T("通讯方式"))
#define IDS_EN_COMPORT					(_T("ComPort"))
#define IDS_CN_COMPORT					(_T("串口"))
#define IDS_EN_BAUDRATE					(_T("Baudrate"))
#define IDS_CN_BAUDRATE					(_T("波特率"))
#define IDS_EN_DST_DEVICE_ID			(_T("Dst Device ID"))
#define IDS_CN_DST_DEVICE_ID			(_T("目标设备ID"))
#define IDS_EN_FP_COUNT					(_T("Fp Count"))
#define IDS_CN_FP_COUNT					(_T("指纹容量"))
#define IDS_EN_LANGUAGE					(_T("Language"))
#define IDS_CN_LANGUAGE					(_T("语言"))
#define IDS_EN_IMAGE_TYPE				(_T("Image Type :"))
#define IDS_CN_IMAGE_TYPE				(_T("图像类别 :"))
#define IDS_EN_ENROLL_FROM_IMAGE		(_T("Enroll Image"))
#define IDS_CN_ENROLL_FROM_IMAGE		(_T("从图像注册"))
#define IDS_EN_SHOW_IMAGE				(_T("Show Image"))
#define IDS_CN_SHOW_IMAGE				(_T("预览图像"))
#define IDS_EN_ADVANCED_LED				(_T("Advanced Led"))
#define IDS_CN_ADVANCED_LED				(_T("特需灯控制"))
#define	IDS_EN_SECURE_COMM				(_T("Secure Comm"))
#define	IDS_CN_SECURE_COMM				(_T("安全通讯"))
#define IDS_EN_ENROLL_COUNT				(_T("Enroll Count :"))
#define IDS_CN_ENROLL_COUNT				(_T("图像数量 :"))
#define IDS_EN_GET_ENROLLED_ID_LIST		(_T("Get Enrolled ID List"))
#define IDS_CN_GET_ENROLLED_ID_LIST		(_T("获取已注册用户列表"))
#define IDS_EN_ENTER_STANDBY			(_T("Enter Standby"))
#define IDS_CN_ENTER_STANDBY			(_T("进入休眠"))
#define IDS_EN_ADJUST_SENSOR			(_T("Adjust Sensor"))
#define IDS_CN_ADJUST_SENSOR			(_T("初始化传感器"))
#define IDS_EN_UPGRADE_FIRMWARE			(_T("Upgrade"))
#define IDS_CN_UPGRADE_FIRMWARE			(_T("升级固件"))
#define IDS_EN_GROUP_RTC				(_T("RTC Control"))
#define IDS_CN_GROUP_RTC				(_T("RTC控制"))
#define IDS_EN_SET_RTC					(_T("Set RTC"))
#define IDS_CN_SET_RTC					(_T("设置RTC"))
#define IDS_EN_GET_RTC					(_T("Get RTC"))
#define IDS_CN_GET_RTC					(_T("获取RTC"))
