//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OEMHost.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDD_SELECT_MODE_DIALOG          131
#define IDD_DEMO_MODE_DIALOG            132
#define IDD_OEMHOST_DIALOG              133
#define IDC_BN_OPEN_PORT                1000
#define IDC_BN_CLOSE_PORT               1001
#define IDC_BUTTON_SAVE                 1002
#define IDC_SET_DAT                     1003
#define IDC_CHECK1                      1004
#define IDC_BUTTON_SAVE2                1004
#define IDC_SECURITY_LEVEL_CHECK        1004
#define IDC_CHECK_GENERATE_RANDOM_KEY   1004
#define IDC_CHECK_TOUCH_SENSING         1004
#define IDC_CHK_SHOW_IMAGE              1004
#define IDC_BUTTON_FPCANCEL             1005
#define IDC_DEVICE_ID_CHECK             1005
#define IDC_CHK_SHOW_IMAGE2             1005
#define IDC_CHK_ADVANCED_LED            1005
#define IDC_COMBO_SETBAUDRATE           1006
#define IDC_DUPLICATION_CHECK           1006
#define IDC_COMBO_SETMODE               1007
#define IDC_COMBO_MODE                  1007
#define IDC_BAUDRATE_CHECK              1007
#define IDC_BUTTON_SLED                 1008
#define IDC_ADC_POWER_CONTROL_CHECK     1008
#define IDC_SEND_CMD                    1009
#define IDC_AUDIO_POWER_CONTROL_CHECK   1009
#define IDC_CMD_PKT                     1010
#define IDC_WIEGAND_CONFIGURE_CHECK     1010
#define IDC_GPIO15_CONFIGURE_CHECK      1011
#define IDC_SET_DEVICE_PARAM_BTN        1012
#define IDC_GET_DEVICE_PARAM_BTN        1013
#define IDC_SEC_LEVEL_CMB               1014
#define IDC_DUP_CHECK_CMB               1015
#define IDC_BAUDRATE_CMB                1016
#define IDC_BTN_GET_FP_NO               1016
#define IDC_RCM_PKT                     1017
#define IDC_GPIO16_CONFIGURE_CHECK      1017
#define IDC_BTN_ENROLL_FP               1017
#define IDC_ADC_POWERCONTROL_CMB        1018
#define IDC_BTN_AUTO_ENROLL             1018
#define IDC_AUDIO_POWER_CONTROL_CMB     1019
#define IDC_BTN_CLEAR_ALL_FP            1019
#define IDC_WIEGAND_MODE_CMB            1020
#define IDC_BTN_CLEAR_FP                1020
#define IDC_GPIO15_CONFIGURE_CMB        1021
#define IDC_DEVICE_ID_EDIT              1022
#define IDC_FINGER_NO_EDIT              1023
#define IDC_CONNECT_STATUS              1024
#define IDC_GPIO16_CONFIGURE_CMB        1024
#define IDC_SECURITY_LEVEL              1025
#define IDC_ENROLL_FP_BTN               1025
#define IDC_FP_TIME_OUT_VALUE           1026
#define IDC_OPEN_FP_DATA_BTN            1026
#define IDC_RESPONSE                    1027
#define IDC_OPER_MODE                   1027
#define IDC_SAVE_FP_DATA_BTN            1027
#define IDC_RESULT_MESSAGE              1028
#define IDC_RCM_CODE                    1029
#define IDC_WIEGAND_IO_STATE_CMB        1029
#define IDC_RCM_LEN                     1030
#define IDC_STANDBY_TIME_OUT_VALUE2     1030
#define IDC_VERIFY_FP_BTN               1030
#define IDC_RCM_DAT1                    1031
#define IDC_IDENTIFY_FP_BTN             1031
#define IDC_RCM_DAT2                    1032
#define IDC_IDENTIFY_FREE_FP_BTN        1032
#define IDC_RCM_CKS                     1033
#define IDC_FP_GENERATION_COUNT_CMB     1033
#define IDC_ENROLL_ID_EDIT              1034
#define IDC_CMD_CODE                    1035
#define IDC_CHANGE_FP_BTN               1035
#define IDC_CMD_LEN                     1036
#define IDC_CLEAR_FP_BTN                1036
#define IDC_CMD_DAT                     1037
#define IDC_CLEAR_ALL_FP_BTN            1037
#define IDC_CMD_CKS                     1038
#define IDC_GET_ENROLL_FP_COUNT_BTN     1038
#define IDC_TEMP_PATH                   1039
#define IDC_GET_FP_STATUS_BTN           1039
#define IDC_SEL_COMPORT                 1040
#define IDC_SEL_BAUDRATE                1041
#define IDC_SEL_CMD                     1042
#define IDC_GET_BROKEN_FP_ID_BTN        1042
#define IDC_TEMP_PATH2                  1043
#define IDC_READ_FP_DATA_BTN            1043
#define IDC_WRITE_FP_DATA_BTN           1044
#define IDC_GET_ENROLL_ID_BTN           1045
#define IDC_GET_FW_VERSION_BTN          1046
#define IDC_SET_ENROLL_ID_BTN           1046
#define IDC_RCM_CODE_LABEL              1047
#define IDC_FINGER_DETECT_BTN           1047
#define IDC_GET_DEVICE_NAME_BTN         1048
#define IDC_DAT_LABEL                   1049
#define IDC_SET_DEV_PASS_BTN            1049
#define IDC_TEMP_PATH_LABEL             1050
#define IDC_AUTHORIZE_DEV_PASS_BTN      1050
#define IDC_TEMP_PATH_LABEL2            1051
#define IDC_GET_ADC_VALUE_BTN           1051
#define IDC_AUDIO_PLAYBACK_BTN          1052
#define IDC_SET_WIEGAND_OUTPUT_BTN      1053
#define IDC_GET_WIEGAND_INPUT_BTN       1054
#define IDC_SET_LED_OUTPUT_BTN          1055
#define IDC_SET_GPIO_OUTPUT_BTN         1055
#define IDC_GET_GPIO15_INPUT_BTN        1056
#define IDC_GET_GPIO_INPUT_BTN          1056
#define IDC_SET_GPIO15_OUTPUT_BTN       1057
#define IDC_ADJUST_SENSOR_BTN           1057
#define IDC_SHOW_SEC_LEVEL_EDIT         1058
#define IDC_DEV_PASSWORD_EDIT           1059
#define IDC_WIEGAND_VALUE_EDIT          1060
#define IDC_FP_DATA_EDIT                1061
#define IDC_AUDIO_NO_EDIT               1062
#define IDC_LED_ON_TIME_EDIT            1063
#define IDC_LED_OFF_TIME_EDIT           1064
#define IDC_LED_CYCLE_EDIT              1065
#define IDC_FP_DATA_PATH1_EDIT          1066
#define IDC_FP_DATA_PATH2_EDIT          1067
#define IDC_VERIFY_FP_DATA_WITH_CAPTRUED_FP_BTN 1068
#define IDC_IDENTIFY_FP_DATA_WITH_CAPTRUED_FP_BTN 1069
#define IDC_GET_FP_DATA_OF_CAPTURED_FP_BTN 1070
#define IDC_OPEN_FP_DATA1_BTN           1071
#define IDC_OPEN_FP_DATA2_BTN           1072
#define IDC_FP_TIMEOUT_EDIT             1073
#define IDC_SET_FP_TIMEOUT_BTN          1074
#define IDC_SHOW_FP_TIMEOUT_EDIT        1075
#define IDC_GET_EMPTY_FP_ID_BTN         1076
#define IDC_SLED_ON_BTN                 1077
#define IDC_SLED_OFF_BTN                1078
#define IDC_FP_CANCEL_BTN               1079
#define IDC_GPIO15_LEVEL_CMB            1080
#define IDC_SET_IDENTIFY_FREE_MODE_BTN  1080
#define IDC_CLEAR_DEV_PASS_BTN          1081
#define IDC_CONTINUOUS_GET_IMAGE_BTN    1081
#define IDC_GET_ADC_VALUE_BTN2          1082
#define IDC_WIEGAND_IO_STATE_CMB2       1082
#define IDC_GPIO_PORT_CMB               1083
#define IDC_GPIO_LEVEL_CMB              1084
#define IDC_ADC_TYPE_CMB                1085
#define IDC_BTN_UP_FP_IMAGE             1086
#define IDC_DESTINATION_DEVICE_ID_EDIT  1087
#define IDC_SOURCE_DEVICE_ID_EDIT       1088
#define IDC_RADIO_SERIAL_COMM           1090
#define IDC_RADIO_USB_COMM              1091
#define IDC_WND_FINGER                  1092
#define IDC_CHECK2                      1093
#define IDC_CHK_IMG_STRETCH             1093
#define IDC_BTN_SAVE_FINGER_IMAGE       1094
#define IDC_AUTO_LEARN_CHECK            1095
#define IDC_BTN_OPN_FINGER_IMAGE        1095
#define IDC_AUTO_LEARN_CMB              1096
#define IDC_BTN_DEMO_MODE               1097
#define IDC_BTN_DEVELOP_MODE            1098
#define IDC_BTN_CONNECT                 1099
#define IDC_EDIT_FP_ID                  1100
#define IDC_EDIT_FINGER_NO              1101
#define IDC_BTN_VERIFY_FP               1102
#define IDC_BTN_IDENTIFY_FP             1103
#define IDC_BTN_FREE_IDENTIFY           1104
#define IDC_BTN_OP_CANCEL               1106
#define IDC_LIST_FP_TEMPLATE            1107
#define IDC_CMB_COMPORT                 1111
#define IDC_CMB_BAUDRATE                1112
#define IDC_EDIT_SOURCE_DEVICE_ID       1113
#define IDC_CMB_SET_BAUDRATE            1113
#define IDC_EDIT_DESTINATION_DEVICE_ID  1114
#define IDC_CMB_BAUDRATE2               1114
#define IDC_CMB_MAX_FP_COUNT            1114
#define IDC_CMB_SEC_LEVEL               1116
#define IDC_CMB_DUP_CHECK               1118
#define IDC_CMB_AUTO_LEARN              1120
#define IDC_BTN_SET_DEVICE_PARAM        1121
#define IDC_BTN_GET_DEVICE_PARAM        1122
#define IDC_CHK_VIEW_FP_IMAGE           1123
#define IDC_BTN_DISCONNECT              1124
#define IDC_WND_RESULT                  1126
#define IDC_TEXT_FP_TEMPLATE            1127
#define IDC_LIST_COMMAND                1128
#define IDC_EDIT_COMMAND_PACKET         1129
#define IDC_EDIT_RESULT                 1129
#define IDC_EDIT_RECEIVED_PACKET        1130
#define IDC_EDIT_PACKET_DATA            1130
#define IDC_EDIT_FP_DATA                1131
#define IDC_BTN_OPEN_TEMPLATE           1132
#define IDC_BTN_SAVE_TEMPLATE           1133
#define IDC_EDIT_PARAM1                 1136
#define IDC_EDIT_PARAM2                 1137
#define IDC_EDIT_PARAM3                 1138
#define IDC_EDIT_PARAM4                 1139
#define IDC_BTN_SEND_COMMAND            1141
#define IDC_BTN_STOP                    1142
#define IDC_BTN_ENTER_IAP_MODE          1143
#define IDC_CMB_PARAM1                  1144
#define IDC_CMB_PARAM3                  1145
#define IDC_CMB_PARAM2                  1146
#define IDC_CMB_PARAM4                  1147
#define IDC_RADIO_COMMAND               1148
#define IDC_RADIO_FUNCTION              1149
#define IDC_LABEL_PARAM1                1150
#define IDC_LABEL_PARAM2                1151
#define IDC_LABEL_PARAM3                1152
#define IDC_LABEL_PARAM4                1153
#define IDC_EDIT_COMM_KEY               1154
#define IDC_EDIT_DEV_PASS               1156
#define IDC_BTN_OPEN_FILE1              1157
#define IDC_BTN_OPEN_FILE2              1158
#define IDC_COMBO1                      1158
#define IDC_EDIT1                       1159
#define IDC_BTN_SET_PARAM               1160
#define IDC_BTN_GET_PARAM               1161
#define IDC_EDIT_USER_ID                1162
#define IDC_EDIT_ID_NOTE                1163
#define IDC_BTN_ENROLL                  1164
#define IDC_BTN_VERIFY                  1165
#define IDC_BTN_IDENTIFY                1166
#define IDC_BTN_IDENTIFY_TEMPLATE       1167
#define IDC_COMBO2                      1168
#define IDC_BTN_VERIFY_WITH_DOWN_TMPL   1169
#define IDC_BTN_IDENTIFY_IMAGE          1170
#define IDC_BTN_DETECT_FINGER           1171
#define IDC_BTN_UP_IMAGE                1172
#define IDC_BTN_GET_USER_COUNT          1173
#define IDC_BTN_DELETE_ID               1174
#define IDC_BTN_UP_TEMPLATE             1175
#define IDC_BTN_DOWN_TEMPLATE           1176
#define IDC_BTN_GET_BROKEN_ID           1177
#define IDC_BTN_GET_DEVICE_INFO         1178
#define IDC_BTN_GET_EMPTY_ID            1179
#define IDC_BTN_GET_STATUS              1180
#define IDC_BTN_DELETE_ALL              1181
#define IDC_BTN_DOWN_MULTI_TMPL         1182
#define IDC_BTN_SET_ID_NOTE             1183
#define IDC_BTN_ENROLL_FROM_IMAGE       1183
#define IDC_BTN_GET_ID_NOTE             1184
#define IDC_BTN_DOWN_MULTI_TMPL2        1184
#define IDC_BTN_GET_ENROLLED_ID_LIST    1184
#define IDC_BTN_SET_MODULE_SN           1185
#define IDC_BTN_GET_MODULE_SN           1186
#define IDC_EDIT_MODULE_SN              1187
#define IDC_RADIO_COMM_SERIAL           1188
#define IDC_RADIO_COMM_USB              1189
#define IDC_EDIT_DEVPASS                1190
#define IDC_BTN_ENROLL_FROM_IMAGE2      1190
#define IDC_BTN_ADJUST_SENSOR           1190
#define IDC_BTN_SET_DEVPASS             1191
#define IDC_BTN_DOWN_MULTI_TMPL3        1191
#define IDC_BTN_UP_MULTI_TMPL           1191
#define IDC_BTN_VERIFY_DEVPASS          1192
#define IDC_BTN_CLEAR_DEVPASS           1193
#define IDC_RADIO_CHINESE               1193
#define IDC_EDIT_USER_ID2               1194
#define IDC_EDIT_DEVICE_ID              1194
#define IDC_RADIO_CHINESE2              1195
#define IDC_RADIO_ENGLISH               1195
#define IDC_LB_PARAM_TYPE               1196
#define IDC_LB_PARAM_VALUE              1197
#define IDC_GROUP_RECEIVED_RESULT       1198
#define IDC_GROUP_FINGER_IMAGE          1199
#define IDC_GROUP_TEMPLATE              1200
#define IDC_GROUP_COMM_INFO             1201
#define IDC_GROUP_CON_MODE              1202
#define IDC_LB_COMPORT                  1203
#define IDC_LB_BAUDRATE                 1204
#define IDC_LB_DST_DEVICE_ID            1205
#define IDC_LB_FP_COUNT                 1206
#define IDC_GROUP_LANGUAGE              1207
#define IDC_LB_IMAGE_TYPE               1208
#define IDC_CMB_ENROLL_COUNT            1209
#define IDC_LB_ENROLL_COUNT             1210
#define IDC_BUTTON1                     1211
#define IDC_BTN_ENTER_STANDBY           1211
#define IDC_BUTTON2                     1212
#define IDC_BUTTON_UPGRADE              1212
#define IDC_EDT_IMG_WIDTH               1213
#define IDC_EDIT3                       1214
#define IDC_EDT_IMG_HEIGHT              1214
#define IDC_BTN_SET_RTC                 1215
#define IDC_DTP_DATE                    1216
#define IDC_BTN_ENTER_STANDBY3          1217
#define IDC_BTN_GET_RTC                 1217
#define IDC_DTP_TIME                    1218
#define IDC_GROUP_RTC                   1221
#define IDC_CHK_SECURE_COMM             1222

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1223
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
